name: B0003 Variabesの使い方 初級編[001]
run-name: WorkFlow Dispatch Parttern.
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
jobs:
  job01:
    runs-on: ubuntu-latest
    env:
      FIRST_NAME: Maki(Job)
      LAST_NAME: Azuki(Job)
    steps:
      - name: Stepでのenv定義
        run: echo "My Name is ${FIRST_NAME} ${LAST_NAME}"
        env:
          FIRST_NAME: Maki(Step)
          LAST_NAME: Azuki(Step)
    steps:
      - name: JobでのEnv定義
        run: echo "My Name is ${FIRST_NAME} ${LAST_NAME}"
