name: B003 Variabesの使い方 初級 [変数を定義して出力する]編
run-name: WorkFlow Dispatch Parttern.
on:
  workflow_dispatch:
    inputs:
      FirstName:
        description: 'FirstName'
        type: string
        default: Maki(Input)
        required: false
      LastName:
        description: 'LastName'
        type: string
        default: Azuki(Input)
        required: false
env:
  FIRST_NAME: Maki(WF)
  LAST_NAME: Azuki(WF)
jobs:
  job01:
    runs-on: ubuntu-latest
    steps:
      - name: Inputで定義された変数の出力(オーバーライド関係なし)
        run: echo "My Name is ${{inputs.FirstName}} ${{inputs.LastName}}"
      - name: Workflowで定義された変数の出力
        run: echo "My Name is ${FIRST_NAME} ${LAST_NAME}"
  job02:
    runs-on: ubuntu-latest
    env:
      FIRST_NAME: Maki(Job)
      LAST_NAME: Azuki(Job)
    steps:
      - name: Stepで定義されたenv定義
        run: echo "My Name is ${FIRST_NAME} ${LAST_NAME}"
        env:
          FIRST_NAME: Maki(Step)
          LAST_NAME: Azuki(Step)
      - name: Jobで定義されたenv定義
        run: echo "My Name is ${FIRST_NAME} ${LAST_NAME}"
