name: B003 Variabesの使い方 初級 [変数を定義して出力する]編
run-name: WorkFlow Dispatch Parttern.
on:
  workflow_dispatch:
    inputs:
      FirstName:
        description: 'FirstName'
        type: input
        default: Maki(Input)
        required: false
      LastName:
        description: 'LastName'
        type: input
        default: Azuki(Input)
        required: false
jobs:
  job01:
    runs-on: ubuntu-latest
    env:
      FIRST_NAME: Maki(Job)
      LAST_NAME: Azuki(Job)
    steps:
      - name: Inputでの変数定義
        run: echo "My Name is ${inputs.FirstName} ${inputs.LastName}"
      - name: Stepでのenv定義
        run: echo "My Name is ${FIRST_NAME} ${LAST_NAME}"
        env:
          FIRST_NAME: Maki(Step)
          LAST_NAME: Azuki(Step)
      - name: JobでのEnv定義
        run: echo "My Name is ${FIRST_NAME} ${LAST_NAME}"
