name: B005 Jobs [Jobsの実行コントール]
run-name: Jobs [Jobsの実行コントール]
on:
  workflow_dispatch:
env:
  is_deploy: true
jobs:
  Deploy:
    if: ${is_deploy} == true
    runs-on: ubuntu-latest
    steps:
      - name: 変数is_deployがtrueの場合は実行される
        run: echo is_deploy is true
  Deploy2:
    runs-on: ubuntu-latest
    steps:
      - name: 変数is_deployがtrueの場合は実行される
        run: echo is_deploy is true
