name: B005 Jobs [Jobsの実行コントール]
run-name: Jobs [Jobsの実行コントール]
on:
  workflow_dispatch:
    inputs:
      is_deploy:
        description: 'is_deploy'
        type: boolean
        default: true
        required: true
jobs:
  Deploy:
    if: ${{ inputs.is_deploy == true }}
    runs-on: ubuntu-latest
    steps:
      - name: 変数is_deployがtrueの場合は実行される
        run: echo is_deploy is ${{ inputs.is_deploy}}
  DeployNeeds:
    needs: [Deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Job Deployが実行された場合実行される。
        run: echo is_deploy is ${{ inputs.is_deploy}}
  Parallel:
    runs-on: ubuntu-latest
    steps:
      - name: Job Deployの実行有無関係無しに並列実行される
        run: echo is_deploy is ${{ inputs.is_deploy}}

#    if: ${{ inputs.is_deploy == 'true' }}
#        type: string
