name: B005 Jobs [Jobsの実行コントール]
run-name: Jobs [Jobsの実行コントール]
on:
  workflow_dispatch:
    inputs:
      is_deploy:
        description: 'is_deploy'
        type: string
        default: Go
        required: true
jobs:
  Deploy:
    if: ${{ inputs.is_deploy == 'Go' }}
    runs-on: ubuntu-latest
    steps:
      - name: 変数is_deployがtrueの場合は実行される
        run: echo is_deploy is ${{ inputs.is_deploy}}
