######################
# 説明 : Step/Job間の値の受け渡し方法について学ぶ
#        ここでは新しくjob.<job_id>.idのコンテキストを学びます。
######################

name: B006 Jobs [値の格納と受け渡しについて]
run-name: Jobs [値の格納と受け渡しについて]
on:
  workflow_dispatch:
jobs:
  StepControl:
    runs-on: ubuntu-latest
    steps:
      - name: Step間で値を受け渡すだけであればGITHUB_ENVを使えば良い。(JOB間では通用しない)
        id: step1
        run: |
          LastName="Azuki"
          echo "FirstName=Maki" >> "$GITHUB_ENV"
          echo "LastName=${LastName}" v
      - name: 格納した値を出力させます。
        run: |
          echo "${LastName} <= 同じコンテキストではない為、空が出力される。"
          echo "My Name is ${{ env.FirstName}} ${{ env.LastName}}"
