######################
# 説明 : ここでは再利用workflowの基本を学びます。
#        Workflowの実行と戻り値の使い方を知りましょう
######################

name: B007 Jobs [値の格納と受け渡しについて]
run-name: Jobs [値の格納と受け渡しについて]
on:
  workflow_dispatch:
jobs:
  CallWfOutFullName01:
    uses: ./.github/workflows/WF_B007.yml
  OutputValue:
    runs-on: ubuntu-latest
    needs: [CallWfOutFullName01]
    steps:
      - run: |
          echo "My name is ${{CallWfOutFullName01.outputs.out_FirstName}} ${{CallWfOutFullName01.outputs.out_LastName}}"
