######################
# 説明 : ここでは再利用workflowの基本を学びます。
#        Workflowの実行と戻り値の使い方を知りましょう
######################

name: B007 workflow_call [「再利用ワークフロー」について]
run-name: workflow_call [「再利用ワークフロー」について]
on:
  workflow_dispatch:
jobs:
  CallWfOutFullName01:
    uses: ./.github/workflows/WF_B007.yml
  OutputValue:
    runs-on: ubuntu-latest
    needs: [CallWfOutFullName01]
    steps:
      - run: |
          echo "My name is ${{needs.CallWfOutFullName01.outputs.out_FirstName}} ${{needs.CallWfOutFullName01.outputs.out_LastName}}"
